### ISSUE TITLE
parser.set_defaults(load_size=parser.get_default('crop_size'))

### ISSUE THREAD

**Issue by yu-zj** [SYLan2019/MRRNet#1]
why parser.get_default('crop_size')  equal none？

**Comment by ComingPeopleHW** [comment]
We believe that the parameter 'crop_size' actually will not affect the program. Please feel free to contact us if you have any other questions.

**Comment by ComingPeopleHW** [comment]
> why parser.get_default('crop_size') equal none？

We believe that the parameter 'crop_size' actually will not affect the program. Please feel free to contact us if you have any other questions.

**Comment by yu-zj** [comment]
Why"ModuleNotFoundError: No module named 'models.test_model'"?

**Comment by yu-zj** [comment]
Why"ModuleNotFoundError: No module named 'models.test_model'"?
Traceback (most recent call last):
  File "E:/facesuperresolution/1/MRRNet-main/test.py", line 12, in <module>
    opt = TestOptions().parse()  # get test options
  File "E:\facesuperresolution\1\MRRNet-main\options\base_options.py", line 127, in parse
    opt = self.gather_options()
  File "E:\facesuperresolution\1\MRRNet-main\options\base_options.py", line 82, in gather_options
    model_option_setter = models.get_option_setter(model_name)
  File "E:\facesuperresolution\1\MRRNet-main\models\__init__.py", line 50, in get_option_setter
    model_class = find_model_using_name(model_name)
  File "E:\facesuperresolution\1\MRRNet-main\models\__init__.py", line 33, in find_model_using_name
    modellib = importlib.import_module(model_filename)
  File "D:\Anaconda3\envs\test\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
test
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models.test_model'
